name: sliver_vertical_tabbar
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=2.12.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter: