name: lit_vertical_tabbar
description: "Widget that provides automated TabBar changes when ListView is scrolled. (This widget is using ListView to render items for better performance)"
repository: "https://github.com/jcho0216/lit_vertical_tabbar"

version: 0.0.2+1

environment:
  sdk: '>=2.12.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter: